### ISSUE TITLE
Singleton UnloadObserver should be thread-local

### ISSUE THREAD

**Issue by vaadin-miki** [vaadin-miki/super-fields#173]
The instance is shared across multiple instances of `UI`. It should probably be thread-local. There can only be one instance on the client-side, though.

**Comment by jflamy** [comment]
I believe that there is a problem with this approach (I may be reading the code wrong though).  When a page is first served, it will be in thread 123 (say).  The threadlocal variable will belong to that thread.  Every time the page is updated, new threads are fired, but you are keeping a reference to the original thread, preventing 123 from being recovered.

My suggestions would be to attach the listener to the UI object -- it is the UI object that is being unloaded.  Maybe using ComponentUtil.setData  https://vaadin.com/api/platform/14.2.2/com/vaadin/flow/component/ComponentUtil.html#setData-com.vaadin.flow.component.Component-java.lang.Class-T-

**Comment by vaadin-miki** [comment]
this has been overridden by #178
