### ISSUE TITLE
UnloadObserver should belong to the UI that will be unloaded.

### ISSUE THREAD

**Issue by jflamy** [vaadin-miki/super-fields#178]
I believe that there is a problem with the ThreadLocal approach (I may be reading the code wrong though).  When a page is first served, it will be in thread 123 (say).  The threadlocal variable will belong to that thread.  Every time the page is updated, new threads are fired, but you are keeping a reference to the original thread, preventing 123 from being recovered.

My suggestions would be to attach the listener to the UI object -- it is the UI object that is being unloaded.  Maybe using ComponentUtil.setData  https://vaadin.com/api/platform/14.2.2/com/vaadin/flow/component/ComponentUtil.html#setData-com.vaadin.flow.component.Component-java.lang.Class-T-

_Originally posted by @jflamy in https://github.com/vaadin-miki/super-fields/issues/173#issuecomment-651209592_

**Comment by vaadin-miki** [comment]
Thank you for this :) Will fix it this week.

**Comment by jflamy** [comment]
VaadinService.findUI() locates the UI object when serving the request, so that would seem to confirm my intuition - the UI object is persisted between requests and not somehow rebuilt.

**Comment by jflamy** [comment]
I only need the UnloadObserver for my project, so I copied it and updated it to be UI-scoped. 
See https://github.com/jflamy/owlcms4/blob/develop/owlcms/src/main/java/app/owlcms/components/elements/unload/UnloadObserver.java 
 
Sample use for cleaning up on page close is something like this -- ui.add() can be called repeatedly, the observer will only appear once.
```java
public void uiEventBusRegister(Component c, EventBus uiEventBus) {
	UI ui = c.getUI().get();
	uiEventBus.register(c);
		
        UnloadObserver unloadObserver = UnloadObserver.get();
        unloadObserver.addUnloadListener((e) -> {
            logger.warn("closing {}: unregister {} from {}", e.getSource(), c, uiEventBus.identifier());
            try {uiEventBus.unregister(c);} catch (Exception ex) {}
            UnloadObserver.remove();
        });
        ui.add(unloadObserver);
}
```

**Comment by jflamy** [comment]
I will probably add UnloadObserver.addToUI()  to make this clearer.

**Comment by vaadin-miki** [comment]
alright, now the UnloadObserver is basically UI-scoped; it still needs to be added somewhere to some component so that it ends up on the page, but it is associated with any given UI: `UnloadObserver.get()` will be basically the same as `UnloadObserver.get(UI.getCurrent())`

this should fix the problem, I hope
