### ISSUE TITLE
Documentation lagging for UnloadObserver

### ISSUE THREAD

**Issue by jflamy** [vaadin-miki/super-fields#182]
superfields/README.md does not reflect latest changes of UnloadObserver to UI-scoped.
Should include a mention to attach the observer to the UI (typically as a child of UI.getCurrent() in the onAttach event of the view).
Maybe add an UnloadObserver.attach(UI) that would do a get+attach as child ?

**Comment by vaadin-miki** [comment]
documentation in general is a bit lagging behind... yeah, and there also should be a get + add method, but I would rather use a component for it rather than a UI

anyway, this will be part of next release
