### ISSUE TITLE
super-fields addon should not ship with a logging library

### ISSUE THREAD

**Issue by StefanPenndorf** [vaadin-miki/super-fields#226]
Super-Fields currently includes ```slf4j-simple``` which causes problems if you include another slf4j binding in the project. For example we're using logback. Thus application doesn't start because of duplicate binding.

Please consider one of the following alternatives depending on you use case:

1. Completely remove ```slf4j-simple``` -- if you need it for you're demo project please include it there.
2. Move ```slf4j-simple``` Dependency to ```<scope>test</scope>``` -- if you need it for unit and integration tests
3. Declare ```sfl4j-simple``` as ```<optional>true</optional>``` in order to exclude it from transitive inclusion -- if you have a compile time dependency to ```slf4j-simple``` and import and use it's classes (I don't think this case applies here)

**Comment by simasch** [comment]
Yes this is very imporant. All Spring Boot application will have this issue.

**Comment by vaadin-miki** [comment]
thanks for reporting the issue, it will be fixed in the next release

**Comment by vaadin-miki** [comment]
the dependency is now in the demo app only, not in the add-on jar
