### ISSUE TITLE
SuperBigDecimalField loses validation information

### ISSUE THREAD

**Issue by Nazukin-Dmitry** [vaadin-miki/super-fields#241]
Hello, I use SuperBigDecimalField with binder and custom validation logic.
```
       binder.forField(superBigDecimalField)
                .asRequired(text)
                .withValidator(value -> {
                    //logic
                }, text)
                .bind(getter, setter);
```
But after number formatting I don't see any validation error on UI. Only if formatted number looks the same as original(ex. number is "32"), then I see error message.

My little investigation result:
method AbstractSuperNumberField.onFieldBlurred calls TextField.setValue, which fires value change event, which invokes TextField.validate, which makes simple validation(without my custom) and sets that field is valid, although it was invalid because of my validation.
When "formatted number looks the same" TextField.setValue checks that value the same and don't fire event and everything is ok.

**Comment by vaadin-miki** [comment]
thanks for reporting this issue, I will look into it in the coming weeks (the brute force solution seems to be to trigger validation on every blur event, but let's see if I can find something more elegant)

**Comment by AlexeyDomnin** [comment]
Hello!

Is there any progress on this issue?

**Comment by vaadin-miki** [comment]
not that I could report ;)

if you happen to have a unit test that reproduces this issue (or a snippet that I can use to reproduce it), that would be great

I have a plan to work on this during early November

**Comment by vaadin-miki** [comment]
@AlexeyDomnin @Nazukin-Dmitry I am unable to write a sensible unit test for this, so I would appreciate any help; please check the branch `241-validation` (and the commit mentioned just above this comment)

I would appreciate a code snippet that I could reliably replicate the issue with - thanks!

**Comment by Nazukin-Dmitry** [comment]
@vaadin-miki 
I don't know how to correctly simulate user's actions in vaadin unit tests.
Server side _setValue_ method doesn't work in the same way as entering text from browser.
I tried to simulate situation by reflection:
```
    @Test
    public void testBinderAndValidation() {
        @SuppressWarnings("unchecked")
        final Binder<NumberWrapper<T>> binder = new Binder<>((Class<NumberWrapper<T>>)(Class<?>)NumberWrapper.class);
        final NumberValidator<T> validator = new NumberValidator<>();
        validator.setReferenceValue(this.baseTestNumber);
        this.field.setNegativeValueAllowed(true);
        binder.forField(this.field)
                .withValidator(validator)
                .bind("number");
        setValueFromClient(this.negativeTestNumber);
        Assert.assertTrue("field should be invalid, because number is wrong", field.isInvalid());
        this.field.simulateBlur();
        //here test will fail, because after bluring field became valid
        Assert.assertTrue("field should be invalid, because number is wrong", field.isInvalid());
    }

    private void setValueFromClient(Number value) {
        try {
            Class<?> aClass = this.field.getClass();
            while(!aClass.equals(AbstractField.class)) {
                aClass = aClass.getSuperclass();
            }
            Method method = aClass.getDeclaredMethod("setModelValue", Object.class, boolean.class);
            method.setAccessible(true);
            method.invoke(this.field, value, true);
        } catch (Exception e) {
            throw new RuntimeException(e);
        }
    }
```

I can write some sample application to reproduce issue, if you need it.

**Comment by vaadin-miki** [comment]
@Nazukin-Dmitry if it is not a big problem, yes, I would love to have a sample application and that would be greatly appreciated

**Comment by Nazukin-Dmitry** [comment]
Here example
https://github.com/Nazukin-Dmitry/base-starter-spring-gradle/tree/super-fields_241-validation
./gradlew clean bootRun
http://localhost:8080

It looks like this.
![issue-example](https://user-images.githubusercontent.com/15947012/98439690-ac588400-2104-11eb-9f62-86bff6b06005.gif)

**Comment by vaadin-miki** [comment]
@Nazukin-Dmitry many thanks for your help, this is invaluable help :) this and/or next week I will work to fix it

**Comment by vaadin-miki** [comment]
this issue is caused by the fact that the client-side `invalid` flag of the inner text field is not up-to-date with what it should be (I modified the code to also set the flag for the entire field - and one can clearly see that the `super-big-decimal-field` flag has value `true`, but the inner field is `false`)
I suspect it has something to do with pattern validation in the text field, but I am not 100% sure about that, so it needs further investigation

**Comment by vaadin-miki** [comment]
alright, the issue is basically solved (or rather, patched to work around the bug mentioned above) - I still need to update the demo app and fix a problem there, so the coming week should see this go into a 0.9.2 release
