### ISSUE TITLE
Text selection mixin throws JS errors when used in Grid

### ISSUE THREAD

**Issue by kuchtik** [vaadin-miki/super-fields#243]
Hello, I found a problem with SuperBigDecimalField when it is used in grid. Everywhere else it works good for me. I have some form where I need to show grid with some data and each row needs SuperBigDecimalField, where I can change value. It looks like this:

![image](https://user-images.githubusercontent.com/47631674/97855857-b1c85f80-1cfb-11eb-9e04-708dcb13e39b.png)

Here is my code:

```java
final Map<NotificationEvent, Binder<NotificationEvent>> eventBinders = new HashMap<>();
events.forEach(event -> eventBinders.put(event, new Binder<>(NotificationEvent.class)));
Grid<NotificationEvent> grid = new Grid<>(NotificationEvent.class, false);
grid.addColumn(NotificationEvent::getEventType).setHeader("Event type");
grid.addColumn(new ComponentRenderer<>(event -> {
    SuperBigDecimalField limitTextField = new SuperBigDecimalField(event.getLimit(), null, locale, 0);
    limitTextField.withAutoselect(true)
            .withGroupingSeparatorHiddenOnFocus(true)
            .withNullValueAllowed(true)
            .setDecimalFormat(new DecimalFormat("#,##0.##", new DecimalFormatSymbols(locale))));
    eventBinders.get(event).forField(limitTextField)
            .withValidator(value -> value == null || BigDecimal.valueOf(0).compareTo(value) <= 0, "Limit has to be 0 or bigger")
            .bind(NotificationEvent::getLimit, NotificationEvent::setLimit);
    return limitTextField;
})).setHeader("Limit");
// some more columns...
grid.setItems(events);
```

But when I open this form on page, it starts to generate some javascript errors:

![image](https://user-images.githubusercontent.com/47631674/97850752-c05f4880-1cf4-11eb-8862-36a9a973e9f3.png)

And when I click in field, I got some other errors:

![image](https://user-images.githubusercontent.com/47631674/97850867-e1c03480-1cf4-11eb-828d-eb5f868a810c.png)

When I use basic vaadin's BigDecimalField instead it works good. Is there any way to solve this to use your SuperBigDecimalField in this case please? Thank you!

**Comment by vaadin-miki** [comment]
thank you for reporting the issue and for providing sample code; I am no expert in `Grid` (given how wonderfully complex it is)... but let me take a look next week, it is quite important to me that the components work with both grid and binder

**Comment by vaadin-miki** [comment]
first look indicates there is something fishy in the text selection mixin; it also breaks if you use `SuperTextField` instead of the number field

**Comment by vaadin-miki** [comment]
okay, issue is cased during init of a text field, for some reason when `listenToEvents` is called for the first time, the input component to listen to is `undefined`
