### ISSUE TITLE
Add text at caret position

### ISSUE THREAD

**Issue by vaadin-miki** [vaadin-miki/super-fields#290]
A neat feature for `SuperTextArea` and `SuperTextField` - it should be possible to add server-defined text at a current caret position.

A possible problem arising is the text being incompatible with the regular expression assigned to the text field, so that needs to be taken into account.

This feature was suggested by Giovanni Adobati in the Vaadin Directory.

**Comment by ado2000** [comment]
Here you can find some hint
https://github.com/vaadin/vaadin-text-field/issues/515
https://discord.com/channels/732335336448852018/774366825756229632/806915833435258900

**Comment by vaadin-miki** [comment]
Turns out that there is a ready-made JS code for it that is supported by all major browsers: https://developer.mozilla.org/en-US/docs/Web/API/HTMLInputElement/setRangeText

**Comment by vaadin-miki** [comment]
at least the basics of it were easier to implement than I thought, the only thing left being the value change event after the change, I will come back to it in a few days

**Comment by ado2000** [comment]
This can be added to the api
`smsTextArea.getElement().executeJs("this.shadowRoot.querySelector('[part=\"value\"]').setRangeText($0, -1, -1, \"end\");", customField);
`

**Comment by vaadin-miki** [comment]
done, changes merged; @ado2000 fancy checking it out if it works before it gets released? simply clone the project, do a `mvn install` on the `development` branch and depend on version `0.6.66-SNAPSHOT` in whatever custom project you have :) help would be greatly appreciated

even if you do not test it, this feature will be released at some point in April, probably just after Easter

**Comment by vaadin-miki** [comment]
well that took some time.... will be released today with 0.10.2
