### ISSUE TITLE
SuperDateTimePicker breaks Vaadin 20 application

### ISSUE THREAD

**Issue by McPringle** [vaadin-miki/super-fields#298]
In this project, I'm using Vaadin 20.0.1. So it might be a compatibility issue with this new Vaadin version.

```
WARNING in ../target/flow-frontend/super-date-time-picker.js 4:54-68
"export 'DateTimePicker' was not found in '@vaadin/vaadin-date-time-picker/src/vaadin-date-time-picker.js'
 @ ../target/frontend/generated-flow-imports.js
 @ ../target/index.ts
 @ ./generated/vaadin.ts
```

This warning results in the file `index.ts` not being generated and the application is not able to start.

The code using `SuperDateTimePicker` is in the `super-fields` branch of my repo in the file `EventsView.java`:
https://github.com/komunumo/komunumo-server/blob/super-fields/src/main/java/org/komunumo/views/admin/events/EventsView.java

Line 160ff:
```java
final var dateField = new SuperDateTimePicker("Date");
dateField.setDatePattern(new DatePattern("yyyy-MM-dd"));
dateField.setWeekNumbersVisible(true);
dateField.setStep(Duration.ofHours(1));
dateField.setMin(LocalDateTime.now().plusHours(1).withMinute(0));
```

I'm using SuperFields v0.10.1:
```xml
<dependency>
    <groupId>org.vaadin.miki</groupId>
    <artifactId>superfields</artifactId>
    <version>0.10.1</version>
</dependency>
```

Does SuperFields only support LTS releases?

**Comment by vaadin-miki** [comment]
@McPringle please accept my apologies for the delay in responding!

versions of Vaadin above 14 are not supported, as there is a big change in the underlying technology (notably the support for TypeScript); another reason is the quick release pace of main Vaadin versions and the breaking changes between them - so in short, *SuperFields only works with the current LTS version* (and I will do my best to support the next LTS when it comes out - 2022q1 probably)

now, to the actual problem - seems to me that with the addition of type script some additional steps are required to make the application work - and I have no idea what those steps are; also I do not think that downgrading some components (date picker in this case) to a v14 version would work in v20 - I think the best solution if you need to have SuperFields is to downgrade to latest v14 release - sorry if this sounds like a disappointment
