### ISSUE TITLE
Vaadin 14.7.5 and Java8 Support for the new super-fields version

### ISSUE THREAD

**Issue by provi-dominik** [vaadin-miki/super-fields#330]
We will upgrade our project to the current vaadin version (14.7.*), soon.
In this context we want to update the super-fields version, but the new version is not yet available in the .java8 branch.

Can you provide the new super-fields version in the .java8 branch?

**Comment by vaadin-miki** [comment]
thanks for filing the issue and thank you for using my components!

new releases are for java 11 only, but as the changes are minimal, I will try to release next version (0.11.1) also for Java 8 - plans would be to do it this or next week (week 48 of 2021)

**Comment by vaadin-miki** [comment]
@provi-dominik release 0.11.1 (and 0.11.1.java8) will be available in the Vaadin Directory today (2021-11-26) in the evening (about 12 hours from this message)

**Comment by provi-dominik** [comment]
@vaadin-miki Thank you very much for the fast fix!

**Comment by vaadin-miki** [comment]
@provi-dominik it looks like Vaadin Directory no longer allows deploying versions that do not follow semver (for whatever reason) - so while version `0.11.1.java8` is there, it only can be downloaded as a zip (I have no idea who made that change, why they made it and why they thought it is a good idea)

alternatively, you can download the source from github and install it locally to your artifactory/nexus/whatever local library server you have

I guess I will have to look into ways of deploying it to maven central...
