### ISSUE TITLE
ValueChangeMode and clear button

### ISSUE THREAD

**Issue by weiliang2** [vaadin-miki/super-fields#337]
Hi,

the SuperBigDecimalField is really good and handy. 
Any change to support ValueChangeMode and clear button?

**Comment by vaadin-miki** [comment]
hello @weiliang2 - thank you for using my components and apologies for the delay

sure, it is possible for both features to be supported (I have no idea how come I missed them) - I think I might have time to do it still today and then it would be available with the next release (which is scheduled to be this month)

**Comment by vaadin-miki** [comment]
alright, so now I know why I have not implemented it: triggering value change events every time a change happens in the text field causes the grouping separator to be shown - and this is to support typing numbers without them being automatically reformatted

so, I need to find a workaround for that first

**Comment by vaadin-miki** [comment]
it also looks that implementing this will change the behaviour of `set(Minimum|Maximum)FractionDigits` to destructive and I am ok with that, unless I find an elegant workaround

**Comment by vaadin-miki** [comment]
behaviour change: calling `set(Minimum|Maximum)(Fraction|Integer)Digits` is now destructive

number fields implement `HasValueChangeMode`

created `HasClearButton` and added it to number fields, `SuperTextField` and `SuperTextArea`

**Comment by weiliang2** [comment]
hello,

actually setMaximumFractionDigits is also very important. What is a workaround for this?

**Comment by vaadin-miki** [comment]
@weiliang2 currently there is none, but I can start digging into the issue - see #339 

I believe I can make it work ;)
