### ISSUE TITLE
Setting fraction/integer digits should not be destructive

### ISSUE THREAD

**Issue by vaadin-miki** [vaadin-miki/super-fields#339]
Modifying fraction/integer digits should not be destructive to the value of the field.

Introduced as a side effect of implementing #337 - reported there as not wanted.

**Comment by weiliang2** [comment]
Hello,

really appreciate your effort to look into this. Hope to hear some good news.

**Comment by vaadin-miki** [comment]
@weiliang2 according to the tests those changes should now no longer be destructive - will do my best to make a new release this week (or early next week)
