### ISSUE TITLE
CollectionField should filter out empty values when saving the collection

### ISSUE THREAD

**Issue by WoozyG** [vaadin-miki/super-fields#374]
Some Collection implementations choke on null items.  If an entry is blank, it should be filtered out, or at least that should be an option.

As it is, I can't even extend CollectionField to override that code, as the fields List is private, without an accessor. 

generateModelValue() thows an NullPointerException if the collection is a TreeMap, and I can't find a way yet to avoid it other than changing the collection type.

**Comment by vaadin-miki** [comment]
@WoozyG thanks for the bug report! of course the entries should have been filtered, good catch

will add a way to specify a custom filter, as I am pretty sure `MapField` suffers from the same bug and just null-checking will not work

expect a release 0.13.1 some time next week

**Comment by vaadin-miki** [comment]
@WoozyG fixed, will be released with `0.13.1` some time next week, of course you can try the _bleeding edge_ version by cloning and installing `development` branch from this repository

the way it works now is that by default all elements of a collection that are `null` are rejected in the field's value; it is still possible to explicitly allow `null`s in collection by calling `setCollectionElementFilter(null)`

new api defined in `HasCollectionElementFilter<T>` allows for arbitrary filtering of items, also implemented in `MapField` to allow filter of type `Map.Entry<K, V>`

**Comment by WoozyG** [comment]
Great, thanks!  Does this work well with validators?  The demo app will likely show this when it's updated to the new release.  That is, if validation requires X number of items, it will by default validate based on only non-null items, yes?

**Comment by vaadin-miki** [comment]
@WoozyG yes, at least that is my understanding of validation: it uses `getValue()`, which should take into account the filtering
