### ISSUE TITLE
Decimal marker in SuperDoubleField

### ISSUE THREAD

**Issue by jonasrotilli** [vaadin-miki/super-fields#383]
is it possible to define what is the decimal marker in SuperDoubleField?
In Brazil it is different, decimals are represented by a comma and there is a mess in relation to keyboards.
So ideal would be to define what the character is for decimal and also prevent the typing of the thousand.
Example:
I would like the number: 15.000,23
The user could only type the comma of the decimal, or the dot would turn into a comma, that is, he would type 15000.23 or 15000,23 and when leaving the field it is formatted as 15.000,23.

**Comment by vaadin-miki** [comment]
hello @jonasrotilli - thank you for using my components and apologies for the delay in responding (I was on a short holiday break)

the symbols used in the component come from locale, so best way to set them is to use `field.setLocale(...)` with locale proper for Brazil (I believe it will be something like `new Locale("pt", "BR")`) - the demo application uses this approach as well

please try the above and let me know if it worked :)

**Comment by vaadin-miki** [comment]
given no further errors were reported, I am going to close this ticket - please reopen if the above solution does not work :)
