### ISSUE TITLE
Tooltip is not working in SuperLongField

### ISSUE THREAD

**Issue by jcgueriaud1** [vaadin-miki/super-fields#448]
In Vaadin 23.3, there is a new Tooltip component.
A SuperLongField is extending CustomField that implements HasTooltip.
When I'm trying to set the tooltip, the tooltip is created as a component but the tooltip overlay is not created.

**Comment by jcgueriaud1** [comment]
Ok, it's because the tooltip should be attached to the inner field.

In AbstractSuperNumberField, if I add this:
```

    @Override
    public Tooltip setTooltipText(String text) {
        return field.setTooltipText(text);
    }

    @Override
    public Tooltip getTooltip() {
        return field.getTooltip();
    }
```

It's working as expected.

**Comment by vaadin-miki** [comment]
@jcgueriaud1 thanks JC! will add that to the next release

I think superfields still rely on 23.2, but will upgrade it soon
