### ISSUE TITLE
Add support for Vaadin 24 

### ISSUE THREAD

**Issue by jcgueriaud1** [vaadin-miki/super-fields#449]
- [plugin:vite:import-analysis] Failed to resolve import "@vaadin/vaadin-text-field/src/vaadin-text-area" from "frontend/generated/jar-resources/super-text-area.js". Does the file exist?
- setPreventInvalidInput does not exist anymore.

Maybe there are more incompatibilities.

**Comment by arenk** [comment]
Any chance to move forward with the PR now we have a release candidate of Vaadin 24? The issue mentioned in the PR has been resolved as well. Would help a lot with Vaadin 24 testing :)

**Comment by vaadin-miki** [comment]
@arenk in general I would not want to release a version of superfields that works with a release candidate; the practice so far was that Vaadin version gets released, and within a few days I release an updated version of superfields, after I make sure everything works more or less as before; sorry if this feels disappointing - but as soon as v24 is out, this PR gets merged and new release will be made

one reason for me waiting is that this project is seriously lacking in automated ui tests, which would allow me to go full CD; I hope to have time or contributors one day :D

**Comment by arenk** [comment]
Understood. Appreciate your effort, it's a really useful Vaadion add-on!

**Comment by jcgueriaud1** [comment]
I've updated the vaadin version int the PR and enable the vaadin.frontend.hotdeploy in the demo (since it's not convenient when you are developing frontend stuff).

**Comment by vaadin-miki** [comment]
as Vaadin 24 is out, expect a new release for it by the end of next week (but I will do my best to do it this week still)
