### ISSUE TITLE
SuperTextField.inputMode cannot be set inside a Grid.Column

### ISSUE THREAD

**Issue by haenni** [vaadin-miki/super-fields#513]
Entering edit-mode of a grid with SuperBigDecimalField set as editorComponent triggers an error in the browser console:

`TypeError: Cannot set properties of undefined (setting 'inputMode')`

Steps to reproduce:
1) extract reproducer view from attached zip file 
2) access the view from some vaadin project, eg. one of the vaadin-starter projects
3) on the view, double click either one cells of the second column to enter edit mode.
4) observe error in browser console.

superfields 0.19.0
Vaadin 24.3.5
[reproducer_view.zip](https://github.com/vaadin-miki/super-fields/files/15470418/reproducer_view.zip)

**Comment by vaadin-miki** [comment]
hello @haenni - thank you for using my components!

while I have to apologise for the bug, I would like to thank you for your absolutely perfect bug report 🌞 
from what I can see, `Grid` being `Grid` initialises components differently from any other container (see #243) - I think though I should be able to fix it

**Comment by vaadin-miki** [comment]
this issue is now fixed in `development` and will be released as 0.19.1 some time next week

**Comment by haenni** [comment]
@vaadin-miki 
You are welcome :) Thank you for your quick response and the fix. 
Is there already a planned release date for version 0.19.1?

**Comment by vaadin-miki** [comment]
@haenni please accept my apologies for the delay in releasing 0.19.1 - I simply forgot to do it before my holiday 🌞 anyway, 0.19.1 is now released, and the version for Vaadin 14 will be released by the end of the month

**Comment by haenni** [comment]
@vaadin-miki 
No worries, thanks for the release. Will it be made available as maven artifact?

**Comment by vaadin-miki** [comment]
@haenni it should already be available (https://central.sonatype.com/artifact/pl.unforgiven/superfields) - it happened with a delay, because they changed the authentication method to central, so I had to fix that first :) but now everything seems to be ok
