### ISSUE TITLE
JS errors when text field is used in a grid and disabled

### ISSUE THREAD

**Issue by hinder1** [vaadin-miki/super-fields#530]
Hi,
We use SuperBigDecimalField in a grid.
If the SuperBigDecimalField is first disabled and then enabled, we got some JS errors.
This is because the delayed initialization (SuperTextField#performDelayedInitialization) isn't executed as the field is disabled and the communication from the client to the server is blocked.
Is it possible to set @ClientCallable(DisabledUpdateMode.ALWAYS) to SuperTextField#performDelayedInitialization so that the method is always executed?

superfields 0.19.1
Vaadin 24.5.0
[GridError.zip](https://github.com/user-attachments/files/18147368/GridError.zip)

**Comment by vaadin-miki** [comment]
hello @hinder1 and thanks for using superfields

and thanks for a perfect bug ticket, together with reproducable code :) the fix will be added to the next maintenance release, I hope to have time to do it this week still

**Comment by vaadin-miki** [comment]
@hinder1 due to some unexpected gpg error the release is not yet in Maven and I do not have time to look into it today - in the mean time you could use github packages; I will try to get the thing sorted before the year ends - sorry for the trouble

**Comment by hinder1** [comment]
@vaadin-miki Thank you for your quick fix.
No worries, is there already a date for the release in Maven?
